### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by laurenfitch** [dewyman/TranscriptClean#11]
Hi, I'm trying to use TranscriptClean to remove indels from PacBio data. Would you be able to clarify this error? I also included a sample line from the SAM file I'm trying to process.
Thanks!

Run & error:
```
lauren@notebook:~/results$ docker run -v /home/lauren/data:/data -v /home/lauren/results:/results transcriptclean /bin/bash -c "python /TranscriptClean-master/TranscriptClean.py --sam /results/test.sam --genome /data/ref_seqs/barcoded_stlA_amplicon.fa --outprefix /results/tc_ --dryRun"
Reading genome ..............................
Dry run mode: Cataloguing indels.........
Traceback (most recent call last):
  File "/TranscriptClean-master/TranscriptClean.py", line 1023, in <module>
    main()
  File "/TranscriptClean-master/TranscriptClean.py", line 100, in main
    dryRun_recordIndels(samFile, outprefix, genome)
  File "/TranscriptClean-master/TranscriptClean.py", line 980, in dryRun_recordIndels
    transcript = Transcript2(line, genome, spliceAnnot)
  File "/TranscriptClean-master/transcript2.py", line 60, in __init__
    self.NM, self.MD = self.getNMandMDFlags(genome)
  File "/TranscriptClean-master/transcript2.py", line 361, in getNMandMDFlags
    refBase = genome.sequence({'chr': self.CHROM, 'start': genomePos, 'stop': genomePos}, one_based=True) 
  File "/opt/conda/lib/python2.7/site-packages/pyfasta/fasta.py", line 197, in sequence
    assert 'chr' in f and f['chr'] in self, (f, f['chr'], self.keys())
AssertionError: ({'start': 1, 'chr': 'barcoded_stlA_amplicon.dna', 'stop': 1}, 'barcoded_stlA_amplicon.dna', ['barcoded_stlA_amplicon.dna  (2103 bp)'])
```

SAM file:
```
lauren@notebook:~/results$ head test.sam
@HD	VN:1.9	SO:coordinate	pb:3.0.7
@SQ	SN:barcoded_stlA_amplicon.dna	LN:2103
@RG	ID:default	PL:PACBIO	DS:READTYPE=UNKNOWN	PU:default	SM:UnnamedSample	PM:SEQUEL
@PG	ID:pbmm2	PN:pbmm2	VN:1.0.0 (commit 1.0.0)	CL:pbmm2 align data/ref_seqs/barcoded_stlA_amplicon.fa results/ccs_trimmed_filtered.fq results/ctf.bam --preset CCS --sort -o 7
m54328_190509_191658/4260017/ccs	0	barcoded_stlA_amplicon.dna	1	60	595M1D4M1I580M1M385M1I312M3I30M91M3I104M	*	0	AAGCCCGCTTATTTTTTACATGCCAATACAATGTAGGCTGCTCTACACCTAGCTTCTGGGCGAGTTTACGGGTTGTTAAACCTTCGATTCCGACCTCATTAAGCAGCTCTAATGCGCTGTTAATCACTTTACTTTTATCTAATCTAGACATCATTAATTCCTAATTTTTGTTGACACTCTATCATTGATAGAGTTATTTTACCACTCCCTATCAGTGATAGAGAAAAGTGAACTCTAGAAATAATTTTGTTTAACTTTAAGAAGGAGATATACATATGAAAGCTAAAGATGTTCAGCCAACCATTATTATTAATAAAAATGGCCTTATCTCTTTGGAAGATATCTATGACATTGCGATAAAACAAAAAAAAGTAGAAATATCAACGGAGATCACTGAACTTTTGACGCATGGTCGTGAAAAATTAGAGGAAAAATTAAATTCAGGAGAGGTTATATATGGAATCAATACAGGATTTGGAGGGAATGCCAATTTAGTTGTGCCATTTGAGAAAATCGCAGAGCATCAGCAAAATCTGTTAACTTTTCTTTCTGCTGGTACTGGGGACTATATGTCCAAACCTTGTATTAAAGCGTCCAATGTTACTATGTTACTTTCTGTTTGCAAAGGTTGGTCTGCAACCAGACCAATTGTCGCTCAAGCAATTGTTGATCATATTAATCATGACATTGTTCCTCTGGTTCCTCGCTATGGCTCAGTGGGTGCAAGCGGTGATTTAATTCCTTTATCTTATATTGCACGAGCATTATGTGGTATCGGCAAAGTTTATTATATGGGCGCAGAAATTGACGCTGCTGAAGCAATTAAACGTGCAGGGTTGACACCATTATCGTTAAAAGCCAAAGAAGGTCTTGCTCTGATTAACGGCACCCGGGTAATGTCAGGAATCAGTGCAATCACCGTCATTAAACTGGAAAAACTATTTAAAGCCTCAATTTCTGCGATTGCCCTTGCTGTTGAAGCATTACTTGCATCTCATGAACATTATGATGCCCGGATTCAACAAGTAAAAAATCATCCTGGTCAAAACGCGGTGGCAAGTGCATTGCGTAATTTATTGGCAGGTTCAACGCAGGTTAATCTATTATCTGGGGTTAAAGAACAAGCCAATAAAGCTTGTCGTCATCAAGAAATTACCCAACTAAATGATACCTTACAGGACGTTTATTCAATTCGCTGTGCACCACAAGTATTAGGTATAGTGCCAGAATCTTTAGCTACCGCTCGGAAAATATTGGAACGGGAAGTTATCTCAGCTAATGATAATCCATTGATAGATCCAGAAAATGGCGATGTTCTACACGGTGGAAATTTTATGGGGCAATATGTCGCCCGAACAATGGATGCATTAAAACTGGATATTGCTTTAATTGCCAATCATCTTCACGCCATTGTGGCTCTTATGATGGATAACCGTTTCTCTCGTGGATTACCTAATTCACTGAGTCCGACACCCGGCATGTATCAAGGTTTTAAAGGCGTCCAACTTTCTCAAACCGCTTTAGTTGCTGCAATTCGCCATGATTGTGCTGCATCAGGTATTCATAGCCCTCGCCACAGAACAATACAATCAAGATATTGTCAGTTTAGGTCTGCATGCCGCTCAAGATGTTTTAGAGATGGAGCAGAAATTACGCAATATTGTTTCAATGACAATTCTGGTAGTTTGTCAGGCCATTCATCTTCGCGGCAATATTAGTGAAATTGCGCCTGAAACTGCTAAATTTTACCATGCAGTACGCGAAATCAGTTCTCCTTTGATCACTGATCGTGCGTTGGATGAAGATATAATCCGCATTGCGGATGCAATTATTAATGATCAACTTCCTCTGCCAGAAATCATGCTGGAAGAATAACAGCACAAGTGAGCATATACGTAAACTTTGTACCCCGTCACTCAAAGGCGGTAGTACGGGTTTTGCTGCCCGCAAACGGGCTGTTCTGGTGTTGCTAGTTTGTTATCAGAATCGCAGATCCGGCTTCAGCCGGTTTGCCGGCTGAAAGCGCTATTTCTTCCAGAATTGCCATGATTTTTTCCCCACGGGAGGCGTCACTGGCTCCCGTGTTGTCGGCAGCTTTGATTCGATAAGC	~~~s~~~~~~~.~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~d~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~q~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~z~~~~~~~~~v~~~~~~~~~~~~~~~~v~~~~~~~~~~~~~~~~~~~~Z~~~~Y~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~p~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~X~~~~G~~~~~~~~~~~~~~~~~~p~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\~~~~~~~~~~~M~~~~~~~~~~~~~~~~~~|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`~~~~~~~~~~~~~~~~~~Y~~~~~~~~~~~~~~~~~~Z~~~~~~~~~~~~y~~~~~~~~~~~~~~~~~~}~~~~~~~~~~~~~~m~~~~~~~~~~~x~~~~~~v3~m~~C~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~p~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~P~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~4~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~R~~~~~~~~~~~~~~~~y~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~c~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~H~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~m~~~~~~~~~~~~~~~~~u~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|~~~~~~~~~~~~~~~~~~~~~~~~n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~F~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x~~~~~~~~~~~~~~~~p~~~~~~~~~~~~~~~~~~~~~~n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`v~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~I~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~U~~~~~~~~~~v~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~b<'ae~D~A~I~*~~~~/S~~~Z~~tP~IF)j~Q~~~~~~~~~~~~~~~~~~~~~~D~~~~~~~~~~~~~~~~~~~~e~~~~~v~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{~~~~~~~~~~~~~~~~~~~~J~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~	RG:Z:defaultqs:i:0	qe:i:2110	mc:f:98.1043
```

**Comment by dewyman** [comment]
Hi Lauren, 
Thank you for your detailed framing of the problem :) I notice that the chromosome for this read is "barcoded_stlA_amplicon.dna". Is that chromosome present in your reference genome fasta file? If not, that is probably why you are getting the error.

**Comment by laurenfitch** [comment]
Thanks for the quick reply! Yes, the chromosome is there in the reference fasta (there is only one):

```
lauren@rstudio:~$ head data/ref_seqs/barcoded_stlA_amplicon.fa 
>barcoded_stlA_amplicon.dna  (2103 bp)
AAGCCCGCTTATTTTTTACATGCCAATACAATGTAGGCTGCTCTACACCTAGCTTCTGGGCGAGTTTACGGGTTGTTAAA
CCTTCGATTCCGACCTCATTAAGCAGCTCTAATGCGCTGTTAATCACTTTACTTTTATCTAATCTAGACATCATTAATTC
CTAATTTTTGTTGACACTCTATCATTGATAGAGTTATTTTACCACTCCCTATCAGTGATAGAGAAAAGTGAACTCTAGAA
ATAATTTTGTTTAACTTTAAGAAGGAGATATACATATGAAAGCTAAAGATGTTCAGCCAACCATTATTATTAATAAAAAT
GGCCTTATCTCTTTGGAAGATATCTATGACATTGCGATAAAACAAAAAAAAGTAGAAATATCAACGGAGATCACTGAACT
TTTGACGCATGGTCGTGAAAAATTAGAGGAAAAATTAAATTCAGGAGAGGTTATATATGGAATCAATACAGGATTTGGAG
GGAATGCCAATTTAGTTGTGCCATTTGAGAAAATCGCAGAGCATCAGCAAAATCTGTTAACTTTTCTTTCTGCTGGTACT
GGGGACTATATGTCCAAACCTTGTATTAAAGCGTCACAATTTACTATGTTACTTTCTGTTTGCAAAGGTTGGTCTGCAAC
CAGACCAATTGTCGCTCAAGCAATTGTTGATCATATTAATCATGACATTGTTCCTCTGGTTCCTCGCTATGGCTCAGTGG
```

**Comment by dewyman** [comment]
Ah ok, I see the problem. TranscriptClean uses Pyfasta to process the fasta file, and there is a weird issue that comes up when the Fasta header has additional fields in it (in this case, the "(2103 bp)" part). If you change the Fasta header to simply >barcoded_stlA_amplicon.dna then it should work. I will try to add a more informative error message for this in the future.

**Comment by laurenfitch** [comment]
I ran the --dryrun option with that change and it worked well! Thanks!

**Comment by dewyman** [comment]
Wonderful! Feel free to reach out if you have any more questions.
