### ISSUE TITLE
Recommended aligner

### ISSUE THREAD

**Issue by abayega** [dewyman/TranscriptClean#8]
Hi Dewyman,

thank you for this tool. Which aligner and alignment parameters do you recommend? I used gmap for my Nanopore reads with the following parameters but I got an IndexError;
--cross-species --max-intronlength-ends=10000 -n 1 -z sense_force -f samse

Traceback (most recent call last):
  File "/home/banthony/software/TranscriptClean-1.0.4/TranscriptClean.py", line 989, in <module>
    main()
  File "/home/banthony/software/TranscriptClean-1.0.4/TranscriptClean.py", line 140, in main
    correctMismatches(canTranscripts, genome, snps, transcriptErrorLog)
  File "/home/banthony/software/TranscriptClean-1.0.4/TranscriptClean.py", line 555, in correctMismatches
    mergeOperations, mergeCounts = transcript.mergeMDwithCIGAR()
  File "/netmount/ip14_home/banthony/software/TranscriptClean-1.0.4/transcript2.py", line 223, in mergeMDwithCIGAR
    if cigarOperation[cigarIndex] in ("H", "S", "I", "N"):
IndexError: list index out of range

Kindly advise if another aligner for example Minimap2 is better.

Regards,

**Comment by dewyman** [comment]
I actually ran GMAP myself the other day on a sample and saw the same TranscriptClean error that you're getting on the output, so I will try to find a solution to the problem as soon as possible. In the meantime, I would recommend trying the Minimap2 aligner.

**Comment by dewyman** [comment]
It turns out that the bug was related to how GMAP deals with coordinates on the mitochondrial chromosome, which is circular. Before, when TranscriptClean processed transcripts mapped to a particular area of chrM, it interpreted the alignments as going off the edge of the chromosome, resulting in index errors. I have created a new TranscriptClean release (v1.0.5) that avoids this problem, as well as some other edge cases that I saw with GMAP but not with STAR or Minimap. Feel free to try out this new version on your GMAP reads if you like!

**Comment by abayega** [comment]
Thank you very much, I will try it immediately and get back to you...

**Comment by abayega** [comment]
Hi, I realised that there's a typo on ~/TranscriptClean-1.0.5/transcript2.py", line 378, in getNMandMDFlags
    if refBase == "":
UnboundLocalError: local variable 'refBase' referenced before assignment

**Comment by abayega** [comment]
Hi,

I couldn't quickly troubleshoot this one. Might you know why I am getting this error?

Traceback (most recent call last):
  File "/home/banthony/software/TranscriptClean-1.0.5/TranscriptClean.py", line 1008, in <module>
    main()
  File "/home/banthony/software/TranscriptClean-1.0.5/TranscriptClean.py", line 131, in main
    canTranscripts, noncanTranscripts = processSAM(samFile, genome, sjDict, oSam, oFa, transcriptLog, primaryOnly) 
  File "/home/banthony/software/TranscriptClean-1.0.5/TranscriptClean.py", line 206, in processSAM
    t = Transcript2(line, genome, spliceAnnot)
  File "/netmount/ip14_home/banthony/software/TranscriptClean-1.0.5/transcript2.py", line 60, in __init__
    self.NM, self.MD = self.getNMandMDFlags(genome)
  File "/netmount/ip14_home/banthony/software/TranscriptClean-1.0.5/transcript2.py", line 355, in getNMandMDFlags
    currBase = self.SEQ[seqPos]
IndexError: string index out of range

**Comment by dewyman** [comment]
I'm guessing this could be another noncanonical edge case that arises from Oxford Nanopore's higher error rate relative to PacBio. I'll try to do a fix and get back to you as soon as I can.
